on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: check build status
      id: check-build
      run: |
        if BUILD_RESULT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        https://api.github.com/repos/${{ github.repository }}/commits/b0/check-runs \
                        | jq '.check_runs[] | select(.name=="validate") | .conclusion'`
        then
          echo $BUILD_RESULT
          echo "validate-result=$BUILD_RESULT" >> $GITHUB_OUTPUT
        fi
    - name: deploy changes
      if: ${{ steps.check-build.outputs.validate-result }} == 'success'
      run: |
        echo deploying changes
        echo ${{ steps.check-build.outputs.validate-result }}