on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: check build status
      run: |
        echo ${{ github.repository }}
        echo ${{ github.repository.owner }}
        BUILD_RESULT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos${{ github.repository.owner }}/${{ github.repository }}/commits/${{ github.ref_name }}/check-runs \
        | jq '.check_runs[] | select(.name=="validate") | .conclusion'`
        echo $BUILD_RESULT