on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: check build status
      id: check-build
      run: |
        echo ${{ github.repository }}
        echo ${{ github.repository.owner }}
        BUILD_RESULT=`curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/commits/${{ github.ref_name }}/check-runs \
        | jq '.check_runs[] | select(.name=="validate") | .conclusion'`
        echo $BUILD_RESULT
        echo "validate-result=$BUILD_RESULT" >> $GITHUB_OUTPUT
    - name: deploy changes
      if: ${{ steps.check-build.outputs.validate-result }} == 'success'
      run: |
        echo deploying changes
        echo ${{ steps.check-build.outputs.validate-result }}